name       : zram-generator
version    : 1.1.2
release    : 2
source     :
    - https://github.com/systemd/zram-generator/archive/refs/tags/v1.1.2.tar.gz : 506d47acbabffa7013bb40a1f61c6edfa758a7bd55820d06ef49c7bc83dba762
license    : MIT
component  : desktop.core
summary    : Systemd unit generator for zram devices
description: |
    Systemd unit generator for zram devices
networking : yes
builddeps  :
    - pkgconfig(libsystemd)
    - pkgconfig(ruby-3.1)
    - cargo
    - groff
environment: |
    export GEM_PATH=$workdir/gems
    export GEM_HOME=$workdir/gems
    export PATH=$PATH:$GEM_PATH/bin
setup      : |
    gem install ronn-ng
build      : |
    %make CARGOFLAGS="--target-dir=target" build man
install    : |
    make CARGOFLAGS="--target-dir=target" DESTDIR="$installdir" install

    # Default configuration file
    install -Dm00644 $pkgfiles/default.conf $installdir/usr/lib/systemd/zram-generator.conf
